[mirror_servers]
test-client-repo.atm.cl-mirror.net ansible_host=91.98.80.158 ansible_ssh_private_key_file=~/.ssh/id_ed25519
#mirror-server-01 ansible_host=192.168.1.100
# mirror-server-02 ansible_host=192.168.1.101

[mirror_servers:vars]
ansible_user=root
# ansible_ssh_private_key_file=~/.ssh/id_rsa
